# Homework Week1
Please revise the concepts covered in the Videos Well

In [1]:
x=input("enter a number and press enter:- ")
print(x+2)

enter a number and press enter:- 52
54


In [3]:
print(range(10,30,3))
print(range(30,10,-4))

[10, 13, 16, 19, 22, 25, 28]
[30, 26, 22, 18, 14]


In [4]:
x = [0.5, 0.6] 
type(x)

list

In [6]:
x = [True, False]
type(x)

list

In [7]:
x = ("a", "b", "c") 
type(x)

tuple

In [12]:
list1 = [1, 4, 6, 8, 10]
list1[-1]
list1.insert(3,12)# name_of_list(position, element to be inserted)
list1

[1, 4, 6, 12, 8, 10]

In [38]:
x=range(2,100,5)
print sum(x)
import numpy as np
print np.percentile(x,[20,60,90])#pass all wanted percentiles as a list

990
[ 21.   59.   87.5]


In [39]:
q1=np.percentile(x,25)
q2=np.percentile(x,50)
q3=np.percentile(x,75)
IQR=q3-q1
print IQR

47.5


In [40]:
upper_bound=q1-1.5*IQR
lower_bound=q3+1.5*IQR
print(upper_bound);print(lower_bound)

-45.5
144.5


In [50]:
arr=np.array(range(1,7)).reshape(2,3)
print arr
type(arr)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [60]:
print arr[0,2]
print arr[1,:]
print arr[:,1]
print np.mean(arr)

3
[4 5 6]
[2 5]


3.5

In [65]:
x=[2,4,3,5,7,4,11]

for i in x:
    if(i%2!=0):
        print(i)
print("***")
#or
print ([i for i in x if i%2!=0])

3
5
7
11
***
[3, 5, 7, 11]


In [94]:
x=[57,4,13,5,17,42,11,55]

In [95]:
for i in x:
    for j in range(2,i/2+1):
        if(i%j==0):
            break
    else:
        print i

13
5
17
11


In [107]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1,4],[2,5],[3,6]])
print x
print y
mx = np.matrix(x)
my = np.matrix(y) 
mx * my

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


matrix([[14, 32],
        [32, 77]])

In [ ]:
#Average vs Mean      

In [116]:
#define a list
x=[2,4,21,34,22,9,20,58,43,43,23,1]
xx=np.array(x)
print(np.mean(xx))
print(np.median(xx))
print("----------")
#now lets append a outlier to the list
x.append(1200)
xx=np.array(x)
print(np.mean(xx))
print(np.median(xx))
# on addin gthe outlier the median remianined almost same but the mean changed drastically
#hence Mean is influenced by outliers but median is not.

23.3333333333
21.5
----------
113.846153846
22.0
